---

- guard: institution
  roles:
      - name: institution-admin
        label: 'Institution Admin'
        permissions:
            - inquiry@create
            - inquiry@viewOwn
            - inquiry@viewAnyInInstitution
            - inquiry@manageOwn
            - inquiry@manageAnyInInstitution
            - inquiry@viewIncomming
            - inquiry@manageIncomming
            - billing@viewOwn
            - reporting@viewOwn
            - user@viewOwn
            - user@manageOwn

      - name: billing
        label: 'Billing'
        permissions:
            - billing

      - name: reporting
        label: 'Reporting'
        permissions:
            - reporting

    - name: inquiries-outgoing
        label: 'Inquiries:outgoing'
        permissions:
            - inquiry@create
            - inquiry@viewOwn
            - inquiry@manageOwn
            - inquiry@manageAny

    - name: inquiries-incomming
        label: 'Inquiries:incomming'
        permissions:
            - inquiryIncomming@view
            - inquiryIncomming@manage

- guard: admin
  roles:
      - name: super-admin
        label: 'Super Admin'
        permissions:
            - inquiry@viewAny
            - inquiry@manageAny
            - billing@viewAny
            - billing@manageAny
            - reporting@viewAny
            - user@viewAny
            - user@manageAny

      - name: billing
        label: 'Billing'
        permissions:
            - billing@viewAny
            - billing@manageAny

      - name: reporting
        label: 'Reporting'
        permissions:
            - reporting@viewAny


